Aplicación de ReLU
La función de unidad lineal rectificada (o ReLU) es una de las funciones de activación más comunes en el aprendizaje profundo.

Supera los problemas de entrenamiento relacionados con la función sigmoidea aprendida, como el problema de los gradientes evanescentes.

En este ejercicio, comenzarás con una implementación de ReLU en PyTorch. A continuación, calcularás los gradientes de la función.

Instrucciones 1/2
50 XP
1
2
Crear una función ReLU en PyTorch.

In [2]:
import torch

relu_pytorch = torch.nn.ReLU()

print(relu_pytorch)

ReLU()


Aplicación de ReLU
La función de unidad lineal rectificada (o ReLU) es una de las funciones de activación más comunes en el aprendizaje profundo.

Supera los problemas de entrenamiento relacionados con la función sigmoidea aprendida, como el problema de los gradientes evanescentes.

En este ejercicio, comenzarás con una implementación de ReLU en PyTorch. A continuación, calcularás los gradientes de la función.

Instrucciones 2/2
50 XP
2
Calcule el gradiente de la función ReLU para x utilizando la función relu_pytorch() que ha definido y, a continuación, ejecute una pasada hacia atrás
Hallar el gradiente en x.

In [3]:
import torch
import torch.nn as nn

# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

tensor(0.)


Aplicación de Re con fugasLU
Has aprendido que ReLU es una de las funciones de activación más utilizadas en el aprendizaje profundo. Lo encontrará en la arquitectura moderna. Sin embargo, tiene el inconveniente de que los valores de salida son nulos para las entradas negativas y, por lo tanto, los gradientes son nulos. Una vez que un elemento de la entrada es negativo, se pondrá a cero durante el resto del entrenamiento. Leaky ReLU supera este reto utilizando un factor multiplicador para las entradas negativas.

En este ejercicio, implementarás la función leaky ReLU en NumPy y PyTorch y practicarás su uso. Ya se han importado los paquetes numpy como np, torch y torch.nn como nn.



Instrucciones 1/2
50 XP
1
2
Cree una función ReLU con fugas en PyTorch con una pendiente negativa de 0,05.
Llame a la función en el tensor x, que ya ha sido definido para usted.

In [4]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

tensor(-0.1000)


Contar el número de parámetros
Los modelos de aprendizaje profundo son famosos por tener muchos parámetros. Los modelos lingüísticos recientes tienen miles de millones de parámetros. Con más parámetros viene más complejidad computacional y tiempos de entrenamiento más largos, y un profesional del aprendizaje profundo debe saber cuántos parámetros tiene su modelo.

En este ejercicio, calcularás el número de parámetros de tu modelo, primero utilizando PyTorch y después manualmente.

Instrucciones 1/2
50 XP
1
2
Iterar a través de los parámetros del modelo para actualizar la variable total con el número total de parámetros del modelo.

In [5]:
import torch
import torch.nn as nn

# Create a simple model
model = nn.Sequential(
            nn.Linear(10, 100),
            nn.ReLU(),
            nn.Linear(100, 100),
            nn.ReLU(),
            nn.Linear(100, 1)
        )

# Initialize the total number of parameters
total = 0

# Iterate through the model parameters and count them
for p in model.parameters():
    total += p.numel()
    
print(total)

11301


Manipular la capacidad de una red
En este ejercicio, practicarás la creación de redes neuronales con diferentes capacidades. La capacidad de una red refleja el número de parámetros de dicha red. Para ayudarle, se ha implementado una función calculate_capacity(), como se indica a continuación:

def calculate_capacity(model):

  total = 0

  for p in model.parameters():

    total += p.numel()

  return total
Esta función devuelve el número de parámetros de su modelo.

El conjunto de datos con el que está entrenando esta red tiene n_features características y n_classes clases. El paquete torch.nn se ha importado como nn.

Cree una red neuronal con exactamente tres capas lineales y menos de 120 parámetros, que tome como entradas n_features y como salidas n_classes.

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

def calculate_capacity(model):
    total = 0
    for p in model.parameters():
        total += p.numel()
    return total

# Define the number of features and classes
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with less than 120 parameters
model = nn.Sequential(
    nn.Linear(n_features, 20),
    nn.Linear(20, 12),
    nn.Linear(12, 6),
    nn.Linear(6, 4),
    nn.Softmax(dim=1)
)

# Forward pass
output = model(input_tensor)

print(calculate_capacity(model))

538


Cree una red neuronal con exactamente cuatro capas lineales y más de 120 parámetros, que tome como entradas n_features y como salidas n_classes.

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

def calculate_capacity(model):
    total = 0
    for p in model.parameters():
        total += p.numel()
    return total

# Define the number of features and classes
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with more than 120 parameters
model = nn.Sequential(
    nn.Linear(n_features, 20),
    nn.Linear(20, 12),
    nn.Linear(12, 20),
    nn.Linear(20, 12),
    nn.Linear(12, 6),
    nn.Linear(6, 4),
    nn.Softmax(dim=1)
)

# Forward pass
output = model(input_tensor)

print(calculate_capacity(model))

1050


Experimentar con el ritmo de aprendizaje
En este ejercicio, su objetivo es encontrar la tasa de aprendizaje óptima de tal manera que el optimizador pueda encontrar el mínimo de la función no convexa 
 en diez pasos.

Experimentará con tres valores diferentes de velocidad de aprendizaje. Para este problema, pruebe valores de tasa de aprendizaje entre 0,001 y 0,1.

Se le proporciona la función optimize_and_plot() que toma la tasa de aprendizaje como primer argumento. Esta función ejecutará 10 pasos del optimizador SGD y mostrará los resultados.

Pruebe con un valor pequeño de la tasa de aprendizaje, de forma que el optimizador no sea capaz de superar el primer mínimo de la derecha.

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

def optimize_and_plot(learning_rate):
    x = torch.tensor([20.0], requires_grad=True)
    optimizer = optim.SGD([x], lr=learning_rate)

    for _ in range(10):
        optimizer.zero_grad()
        loss = x**4 - 22*x**3 + 108*x**2 - 128*x
        loss.backward()
        optimizer.step()
        print(x)
        
optimize_and_plot(0.001)

tensor([10.2080], requires_grad=True)
tensor([10.7537], requires_grad=True)
tensor([11.2169], requires_grad=True)
tensor([11.5809], requires_grad=True)
tensor([11.8464], requires_grad=True)
tensor([12.0279], requires_grad=True)
tensor([12.1458], requires_grad=True)
tensor([12.2196], requires_grad=True)
tensor([12.2648], requires_grad=True)
tensor([12.2919], requires_grad=True)


Pruebe con un valor grande de la tasa de aprendizaje de forma que el optimizador se salte el mínimo global en -2.

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

def optimize_and_plot(learning_rate):
    x = torch.tensor([20.0], requires_grad=True)
    optimizer = optim.SGD([x], lr=learning_rate)

    for _ in range(10):
        optimizer.zero_grad()
        loss = x**4 - 22*x**3 + 108*x**2 - 128*x
        loss.backward()
        optimizer.step()
        print(x)
        
optimize_and_plot(0.1)

tensor([-959.2000], requires_grad=True)
tensor([3.5910e+08], requires_grad=True)
tensor([-1.8523e+25], requires_grad=True)
tensor([inf], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)


Basándose en los resultados anteriores, pruebe con un valor de tasa de aprendizaje mejor.

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

def optimize_and_plot(learning_rate):
    x = torch.tensor([20.0], requires_grad=True)
    optimizer = optim.SGD([x], lr=learning_rate)

    for _ in range(10):
        optimizer.zero_grad()
        loss = x**4 - 22*x**3 + 108*x**2 - 128*x
        loss.backward()
        optimizer.step()
        print(x)
        
optimize_and_plot(0.09)

tensor([-861.2800], requires_grad=True)
tensor([2.3443e+08], requires_grad=True)
tensor([-4.6379e+24], requires_grad=True)
tensor([inf], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)


Experimentar con el impulso
En este ejercicio, tu objetivo es encontrar el momento óptimo tal que el optimizador pueda encontrar el mínimo de la siguiente función no convexa 
 en 20 pasos. Experimentarás con dos valores de impulso diferentes. Para este problema, la tasa de aprendizaje se fija en 0,01.

Se le proporciona la función optimize_and_plot() que toma la tasa de aprendizaje como primer argumento. Esta función ejecutará 20 pasos del optimizador SGD y mostrará los resultados.

Prueba un primer valor para el impulso tal que el optimizador se atasque en el primer mínimo.

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

momentum = 0.1
optimize_and_plot(momentum)

tensor([-959.2000], requires_grad=True)
tensor([3.5910e+08], requires_grad=True)
tensor([-1.8523e+25], requires_grad=True)
tensor([inf], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)


Pruebe un segundo valor para el impulso tal que el optimizador encuentre el óptimo global.

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

momentum = 0.9
optimize_and_plot(momentum)

tensor([-8792.7998], requires_grad=True)
tensor([2.4519e+12], requires_grad=True)
tensor([-5.3064e+37], requires_grad=True)
tensor([inf], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)
tensor([nan], requires_grad=True)


 Congelar capas de un modelo
Está a punto de ajustar un modelo en una nueva tarea después de cargar los pesos preentrenados. El modelo contiene tres capas lineales. Sin embargo, como su conjunto de datos es pequeño, sólo desea entrenar la última capa lineal de este modelo y congelar las dos primeras capas lineales.

El modelo ya se ha creado y existe en la variable model. Utilizará el método named_parameters del modelo para listar los parámetros del modelo. Cada parámetro se describe mediante un nombre. Este nombre es una cadena con la siguiente convención de nomenclatura: x.name donde x es el índice de la capa.

Recuerde que una capa lineal tiene dos parámetros: el weight y el bias.

Utilice una sentencia if para determinar si el parámetro debe congelarse o no en función de su nombre.
Congela los parámetros de las dos primeras capas de este modelo.

In [20]:
for name, param in model.named_parameters():    
  
    # Check if the parameters belong to the first layer
    if name == '0.weight' or name == '0.bias':
      
        # Freeze the parameters
        param.requires_grad = False
  
    # Check if the parameters belong to the second layer
    if name == '1.weight' or name == '1.bias':
      
        # Freeze the parameters
        param.requires_grad = False

Inicialización de capas
La inicialización de los pesos de una red neuronal ha sido el centro de atención de los investigadores durante muchos años. Cuando se entrena una red, el método utilizado para inicializar los pesos tiene un impacto directo en el rendimiento final de la red.

Como profesional del aprendizaje automático, debe ser capaz de experimentar con diferentes estrategias de inicialización. En este ejercicio, vas a crear una pequeña red neuronal formada por dos capas y vas a decidir inicializar los pesos de cada capa con el método uniforme.

Instrucciones
100 XP
Para cada capa (layer0 y layer1), utilice el método de inicialización uniforme para inicializar los pesos.

In [22]:
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Use uniform initialization for layer0 and layer1 weights
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model = nn.Sequential(layer0, layer1)

print(model)

Sequential(
  (0): Linear(in_features=16, out_features=32, bias=True)
  (1): Linear(in_features=32, out_features=64, bias=True)
)


Uso de la clase TensorDataset
En la práctica, cargar tus datos en un conjunto de datos PyTorch será uno de los primeros pasos que darás para crear y entrenar una red neuronal con PyTorch.

La clase TensorDataset es muy útil cuando su conjunto de datos se puede cargar directamente como una matriz NumPy. Recordemos que TensorDataset() puede tomar una o más matrices NumPy como entrada.

En este ejercicio, practicarás la creación de un conjunto de datos PyTorch utilizando la clase TensorDataset.

torch y numpy ya han sido importados, junto con la clase TensorDataset.

Instrucciones
100 XP
Convierte las matrices NumPy proporcionadas en tensores PyTorch.
Cree un TensorDataset utilizando torch_features y los tensores torch_target proporcionados (en este orden).
Devuelve el último elemento del conjunto de datos.

In [2]:
import numpy as np  # Importing numpy library
import torch  # Importing PyTorch library
from torch.utils.data import TensorDataset  # Importing TensorDataset from PyTorch

np_features = np.array(np.random.rand(12, 8))  # Creating a 2D array with random numbers
np_target = np.array(np.random.rand(12, 1))  # Creating another 2D array with random numbers

# Convert numpy arrays to PyTorch tensors
torch_features = torch.from_numpy(np_features)
torch_target = torch.from_numpy(np_target)

# Create a TensorDataset from the tensors
dataset = TensorDataset(torch_features, torch_target)

# Print the last element of the dataset
print(dataset[-1])

(tensor([0.5655, 0.7144, 0.7414, 0.9860, 0.6539, 0.6737, 0.2035, 0.3294],
       dtype=torch.float64), tensor([0.3986], dtype=torch.float64))


De la carga de datos a la ejecución de un pase de avance
En este ejercicio, crearás un PyTorch DataLoader a partir de un pandas DataFrame y llamarás a un modelo sobre este conjunto de datos. En concreto, ejecutará un pase hacia adelante en una red neuronal. Seguirás trabajando con redes neuronales totalmente conectadas, como has hecho hasta ahora.

Empezarás subconjuntando un DataFrame cargado llamado dataframe, convirtiendo características y objetivos en arrays NumPy, y convirtiendo a tensores PyTorch para crear un conjunto de datos PyTorch.

Este conjunto de datos puede cargarse en PyTorch DataLoader, procesarse por lotes, barajarse y utilizarse para ejecutar un pase hacia delante en una red neuronal totalmente conectada personalizada.

NumPy como np, pandas como pd, torch, TensorDataset(), y DataLoader() han sido importados para usted.

Instrucciones 1/3
35 XP
1
2
3
Extraiga los valores de las características (ph, Sulfate, Conductivity, Organic_carbon) y de los objetivos (Potability) y cárguelos en los tensores adecuados para representar las características y los objetivos.
Usa ambos tensores para crear un conjunto de datos PyTorch usando la clase dataset que es más rápida de usar cuando los tensores no requieren ningún preprocesamiento adicional.

In [4]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Load the dataframe

dataframe = pd.read_csv('/Users/adrianinfantes/Desktop/AIR/CollegeStudies/MachineLearningPath/DataCamp/DevelopLLMs/data/water_potability.csv')

# Extract the features and targets
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].values).float()
target = torch.tensor(dataframe['Potability'].values).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

print(dataset)

Cree un PyTorch DataLoader a partir del TensorDataset creado; este DataLoader debe utilizar un batch_size de dos y shuffle el conjunto de datos.

In [5]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Load the dataframe

dataframe = pd.read_csv('/Users/adrianinfantes/Desktop/AIR/CollegeStudies/MachineLearningPath/DataCamp/DevelopLLMs/data/water_potability.csv')

# Extract the features and targets
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].values).float()
target = torch.tensor(dataframe['Potability'].values).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a DataLoader from the created dataset
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
x, y = next(iter(dataloader))
print(x, y)

tensor([[0.4026, 0.4098, 0.4784, 0.2341],
        [0.6264, 0.7577, 0.4812, 0.3327]]) tensor([1., 0.])


Implemente una pequeña red neuronal totalmente conectada utilizando exactamente dos capas lineales y la dirección nn.Sequential() API, donde el tamaño final de la salida es 1.

In [7]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn

# Load the dataframe

dataframe = pd.read_csv('/Users/adrianinfantes/Desktop/AIR/CollegeStudies/MachineLearningPath/DataCamp/DevelopLLMs/data/water_potability.csv')

# Extract the features and targets
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].values).float()
target = torch.tensor(dataframe['Potability'].values).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a DataLoader from the created dataset
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
x, y = next(iter(dataloader))

# Create a fully connected network with two layers

model = nn.Sequential(
    nn.Linear(4, 8),
    nn.Linear(8, 1)
)
output = model(features)
print(output)

tensor([[-0.3259],
        [-0.3362],
        [-0.3469],
        ...,
        [-0.2855],
        [-0.3753],
        [-0.4132]], grad_fn=<AddmmBackward0>)


Escribir el bucle de evaluación
En este ejercicio, practicarás escribiendo el bucle de evaluación. Recuerde que el bucle de evaluación es similar al bucle de entrenamiento, salvo que no realizará el cálculo del gradiente ni el paso del optimizador.

El model ya ha sido definido para usted, junto con el objeto validationloader, que es un conjunto de datos.

Instrucciones 1/2
50 XP
1
2
Ponga el modelo en modo de evaluación.
Suma la pérdida del lote actual a la variable validation_loss.

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Load the dataframe
dataframe = pd.read_csv('/Users/adrianinfantes/Desktop/AIR/CollegeStudies/MachineLearningPath/DataCamp/DevelopLLMs/data/water_potability.csv')

# Extract the features and targets
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].values).float()
target = torch.tensor(dataframe['Potability'].values).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a DataLoader from the created dataset
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
x, y = next(iter(dataloader))

# Create a fully connected network with two layers
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.Linear(8, 1)
)

# Put the model in evaluation mode
model.eval()

# Initialize the loss function
criterion = nn.BCEWithLogitsLoss()

# Initialize the optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Initialize the validation loss
validation_loss = 0.0

# Iterate over the validation loader
for x, y in dataloader:
    # Forward pass
    output = model(x)
    
    # Compute the validation loss
    loss = criterion(output, y.unsqueeze(1))
    validation_loss += loss.item()
    
print(validation_loss)

699.92709004879


Calcular el valor medio de pérdida de la época.
Vuelve a poner el modelo en modo de entrenamiento.

In [9]:
# Initialize the loss function

criterion = nn.BCEWithLogitsLoss()

# Initialize the optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Initialize the validation loss
validation_loss = 0.0

# Iterate over the validation loader
for x, y in dataloader:
    # Forward pass
    output = model(x)
    
    # Compute the validation loss
    loss = criterion(output, y.unsqueeze(1))
    validation_loss += loss.item()
    
# Compute the average validation loss
validation_loss /= len(dataloader)
print(validation_loss)

# Put the model back in training mode
model.train()

0.6957360357342373


Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=1, bias=True)
)

Cálculo de la precisión mediante torchmetrics
Además de las pérdidas, también debe controlar la precisión durante el entrenamiento. De este modo, podrá seleccionar la época en la que el modelo obtuvo los mejores resultados.

En este ejercicio, practicará el uso del paquete torchmetrics para calcular la precisión. Utilizará una muestra del conjunto de datos de máscaras faciales. Este conjunto de datos contiene tres clases diferentes. La función plot_errors mostrará las muestras en las que las predicciones del modelo no coincidan con la verdad sobre el terreno. Realizar este análisis de errores le ayudará a comprender los modos de fallo de su modelo.

El paquete torchmetrics ya está importado. El modelo outputs son las probabilidades devueltas por un softmax como último paso del modelo. El tensor labels contiene las etiquetas como vectores codificados de un solo golpe.

Instrucciones 1/2
50 XP
1
2
Cree una métrica de precisión para un problema "multiclass" con tres clases.
Calcular la precisión de cada lote del cargador de datos.

In [13]:
# Import torchmetrics
from torchmetrics import Accuracy

# Initialize the accuracy metric
accuracy = Accuracy('multiclass', num_classes=3)  # Para tareas de clasificación multiclase con tres clases

# Initialize the validation loss
validation_loss = 0.0

# Iterate over the validation loader
for x, y in dataloader:
    # Forward pass
    output = model(x)

    # Compute the validation loss
    loss = criterion(output, y.unsqueeze(1))
    validation_loss += loss.item()

    # Compute the accuracy
    acc = accuracy(output, y)
    print(acc)

# Compute the average validation loss
validation_loss /= len(dataloader)
print(validation_loss)

# Put the model back in training mode
model.train()

ValueError: If `preds` have one dimension more than `target`, `preds.shape[1]` should be equal to number of classes.

## Data Augmentation: Aumento de datos

El aumento de datos es una técnica comúnmente utilizada para mejorar el rendimiento de los modelos de aprendizaje profundo. Consiste en aplicar transformaciones aleatorias a los datos de entrenamiento, como rotaciones, recortes, reflejos y cambios de color. De esta manera, el modelo puede aprender a generalizar mejor y a ser más robusto a las variaciones en los datos.

Experimentar con el abandono
La capa de exclusión elimina aleatoriamente los elementos del tensor de entrada. Esto ayuda a combatir el sobreajuste. En este ejercicio, crearás una pequeña red neuronal con al menos dos capas lineales, dos capas de abandono y dos funciones de activación.

El paquete torch.nn ya se ha importado como nn. Un input_tensor de dimensiones  ha sido creado para usted.

Instrucciones 1/2
50 XP
1
Cree una pequeña red neuronal con una capa lineal, una función ReLU y una capa de abandono, en ese orden.
El modelo debe tomar input_tensor como entrada y devolver una salida de tamaño 16.

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Load the dataframe
dataframe = pd.read_csv('/Users/adrianinfantes/Desktop/AIR/CollegeStudies/MachineLearningPath/DataCamp/DevelopLLMs/data/water_potability.csv')

# Extract the features and targets
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].values).float()
target = torch.tensor(dataframe['Potability'].values).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a DataLoader from the created dataset
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
x, y = next(iter(dataloader))

model = nn.Sequential(
    nn.Linear(4, 8), # Capa lineal. 4 entradas, 8 salidas
    nn.ReLU(), # Función de activación. Usamos ReLU como función de activación
    nn.Dropout(0.2), # Capa de abandono. 20% de abandono
    nn.Linear(8, 16) # Capa lineal. 8 entradas, 16 salidas
)

output = model(features)
print(output)

tensor([[-0.1605, -0.0954, -0.4332,  ..., -0.3773,  0.0200,  0.1919],
        [ 0.0390,  0.0697, -0.3228,  ..., -0.3057, -0.1184,  0.0131],
        [-0.1030, -0.0300, -0.4960,  ..., -0.3904, -0.0576,  0.1249],
        ...,
        [ 0.3275,  0.2047, -0.1405,  ..., -0.3456,  0.0696,  0.1859],
        [-0.1550, -0.0499, -0.4954,  ..., -0.3693, -0.0230,  0.1531],
        [-0.1478, -0.0639, -0.5449,  ..., -0.2290,  0.0765,  0.0132]],
       grad_fn=<AddmmBackward0>)


Utilizando la misma red neuronal, establezca la probabilidad de poner a cero elementos en la capa de abandono en 0.8.

In [ ]:
# Create a small neural network

model = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Dropout(0.8),
    nn.Linear(8, 16)
)

output = model(features)
print(output)

Aplicación de la búsqueda aleatoria
La búsqueda de hiperparámetros es un método costoso desde el punto de vista informático para experimentar con diferentes valores de hiperparámetros. Sin embargo, puede mejorar el rendimiento. En este ejercicio, implementarás un algoritmo de búsqueda aleatoria.

Muestreará aleatoriamente 10 valores de la tasa de aprendizaje y el momento a partir de la distribución uniforme. Para ello, utilizará la función np.random.uniform().

Muestrear aleatoriamente un factor de tasa de aprendizaje entre 2 y 4 para que la tasa de aprendizaje (lr) esté acotada entre  y .
Muestre al azar un momento entre 0,85 y 0,99.

In [ ]:
import numpy as np

values = []

# Sample 10 random values for learning rate and momentum
for idx in range(10):
    factor = np.random.uniform(2, 4)
    lr = 10 ** -factor
    
    momentum = np.random.uniform(0.85, 0.99)
    
    values.append((lr, momentum))