Creación de tensores y acceso a los atributos
Los tensores son la principal estructura de datos en PyTorch y serán los bloques de construcción para nuestros modelos de aprendizaje profundo. Comparten muchas similitudes con las matrices NumPy, pero también tienen algunos atributos únicos.

En este ejercicio, practicarás la creación de un tensor a partir de una lista de Python y la visualización de algunos de sus atributos.

Instrucciones 1/2
50 XP
1
2
Comienza importando PyTorch.
Crear un tensor a partir de la lista de Python list_a.

In [3]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

tensor([1, 2, 3, 4])


In [2]:
# Load data from numpy array

import numpy as np

np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


Creación de tensores y acceso a los atributos
Los tensores son la principal estructura de datos en PyTorch y serán los bloques de construcción para nuestros modelos de aprendizaje profundo. Comparten muchas similitudes con las matrices NumPy, pero también tienen algunos atributos únicos.

En este ejercicio, practicarás la creación de un tensor a partir de una lista de Python y la visualización de algunos de sus atributos. 

Instrucciones 2/2
50 XP
2
Muestra el dispositivo tensor.
Muestra el tipo de datos del tensor.

In [4]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


Creación de tensores a partir de matrices NumPy
Los tensores son la estructura de datos fundamental de PyTorch. Puedes crear complejos algoritmos de aprendizaje profundo aprendiendo a manipularlos.

Se ha importado el paquete torch y se han creado dos matrices NumPy, denominadas array_a y array_b. Ambas matrices tienen las mismas dimensiones.

Instrucciones
100 XP
Cree dos tensores, tensor_a y tensor_b, a partir de las matrices NumPy array_a y array_b, respectivamente.
Resta tensor_b de tensor_a.
Realiza una multiplicación por elementos de tensor_a y tensor_b.
Suma los tensores resultantes de los dos pasos anteriores.

In [5]:
# Create two tensors from the arrays

import torch

array_a = [[1, 2], [3, 4]]
array_b = [[5, 6], [7, 8]]

tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  8],
        [17, 28]])


Su primera red neuronal
En este ejercicio, implementarás una pequeña red neuronal que contiene dos capas lineales. La primera capa toma una entrada de ocho dimensiones, y la última capa produce un tensor unidimensional.

Los paquetes torch y torch.nn ya han sido importados.

Instrucciones
100 XP
Crear una red neuronal de capas lineales que tome como entrada un tensor de dimensiones 
 y como salida un tensor de dimensiones 
.
Utilice cualquier dimensión de salida para la primera capa que desee.

In [7]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 20), # 8 input features, 20 output features
    nn.Linear(20, 1) # 20 input features, 1 output feature
)

output = model(input_tensor)
print(output)

tensor([[-1.9788]], grad_fn=<AddmmBackward0>)


Las funciones sigmoidea y softmax
Las funciones sigmoide y softmax son dos de las funciones de activación más populares en el aprendizaje profundo. Ambos suelen utilizarse como último paso de una red neuronal. Las funciones sigmoidales se utilizan para problemas de clasificación binaria, mientras que las funciones softmax suelen emplearse para problemas de clasificación multiclase. Este ejercicio le familiarizará con la creación y el uso de ambas funciones.

Supongamos que tiene una red neuronal que devuelve los valores contenidos en el tensor score como salida previa a la activación. Aplicará funciones de activación a esta salida.

torch.nn ya está importado como nn.

Instrucciones 1/2
50 XP
1
Crea una función sigmoidea y aplícala en input_tensor para generar una probabilidad.

In [9]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid() # sigmoid function
probability = sigmoid(input_tensor) # apply the function to input_tensor
print(probability) # print the result

tensor([[0.6900]])



Crea una función softmax y aplícala en input_tensor para generar una probabilidad.

In [12]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])  # input tensor

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)  # softmax function. dim=-1 calculates the softmax across the last dimension
probabilities = softmax(input_tensor)  # apply the function to input_tensor
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])
